### ISSUE TITLE
aqm.analysis_cell("2023_01_10__17_27_50__ge_flux_sweep.h5")

### ISSUE THREAD

**Issue by SamuelDeleglise** [SamuelDeleglise/quanalys#15]
Doesn't properly strip the .h5 from the directory name (see exception below)

`ValueError: Cannot load data from C:\Users\CryoPc\My Drive\mecaflux\measurements\Cooldown_2023_01_06_CEAv1_die8\\ge_flux_sweep.h5\2023_01_10__17_27_50__ge_flux_sweep.h5`

**Comment by 4cd87a** [comment]
Will be fixed in next push
